server:
  port: 8080
spring:
  application:
    #应用名称 可选
    name: sjiang_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: jiang
      druid.test-while-idle: false
      mysql.usePingMethod: false

  redis:
    host: localhost
    port: 6379
    password: jiang
    database: 0
  cache:
    redis:
      time-to-live: 1800000  #设置缓存的过期时间

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#图片资源保存地址
reggie:
  path: E:\Java\sjiang-project\sjiang_take_out\src\main\resources\backend\upload\